version: '3.8'

services:
  backend:
    build:
      context: ./EasyFD/Core/EasyFD.Api/
      dockerfile: Dockerfile
    ports:
      - "5001:8080" # Map port 5001 on the host to port 8080 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./EasyFD/Web/EasyFD.UI
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    depends_on:
      - backend